# 使用官方 Golang 镜像作为构建阶段的基础镜像
FROM golang:tip-alpine3.21 AS builder

# 设置工作目录
WORKDIR /app

# 将当前目录内容复制到容器的工作目录
COPY . .

# 下载并安装项目依赖
RUN go mod tidy

# 编译 Go 项目
RUN go build -o halalcloud .

FROM alpine

WORKDIR /app
COPY --from=builder /app/halalcloud /usr/bin/halalcloud
CMD ["halalcloud"]
EXPOSE 8080
