FROM node:24-slim as nodebuilder
FROM rclone/rclone:latest AS rclone

FROM python:3.13-slim-trixie

# Set environment variables
ENV DEBIAN_FRONTEND=noninteractive
ARG N8N_PATH=/usr/local/lib/node_modules/n8n
ARG BASE_PATH=/root/.n8n
ARG N8N_PUSH_BACKEND=sse
ARG DATABASE_PATH=$BASE_PATH/database
ARG CONFIG_PATH=$BASE_PATH/config
ARG WORKFLOWS_PATH=$BASE_PATH/workflows
ARG LOGS_PATH=$BASE_PATH/logs
ARG N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=$N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
ARG N8N_HOST=$N8N_HOST
ARG N8N_PORT=$N8N_PORT
ARG N8N_PROTOCOL=https
ARG N8N_EDITOR_BASE_URL=$N8N_EDITOR_BASE_URL
ARG WEBHOOK_URL=$WEBHOOK_URL
ARG GENERIC_TIMEZONE=$GENERIC_TIMEZONE
ARG TZ=$TZ
ARG N8N_ENCRYPTION_KEY=$N8N_ENCRYPTION_KEY
ARG RCLONE_CONF=$RCLONE_CONF


COPY --from=nodebuilder /usr/local/bin/node /usr/local/bin/
COPY --from=nodebuilder /usr/local/lib/node_modules/. /usr/local/lib/node_modules/
COPY --from=rclone /usr/local/bin/rclone /usr/bin/rclone

# Install necessary packages
RUN ln -s /usr/local/lib/node_modules/npm/bin/npm-cli.js /usr/local/bin/npm && \
    apt-get update && \
    apt-get install -y \
    curl \
    sudo \
    build-essential \
    default-jdk \
    default-jre \
    g++ \
    gcc \
    libzbar0t64 \
    fish \
    ffmpeg \
    nmap \
    ca-certificates \
    zsh \
    cron \
    wget \
    tzdata \
    perl \
    openssl \
    openssh-client \
    nginx \
    jq \
    procps \
    netcat-traditional \
    sshpass \
    unzip \
    git \
    make \
    chromium \
    libatomic1 

RUN npm install -g pnpm pm2 n8n

RUN mkdir /n8n-data
RUN chmod -R 777 /var && \
    chmod -R 777 /usr/local && \
    chmod -R 777 /etc/nginx && \
    chmod -R 777 /run && \
    chmod -R 777 /usr && \
    chmod -R 777 /root && \ 
    chmod -R 777 /n8n-data

# Install code-server
RUN curl -fsSL https://code-server.dev/install.sh | sh
#RUN curl -fsSL https://code-server.dev/install.sh | sh -s -- --version=4.23.0-rc.2


USER root

ENV HOME=/root \
    PATH=/root/.local/bin:$PATH

COPY  start_server.sh $HOME
COPY  apps.conf $HOME
COPY  nginx.conf $HOME

RUN chmod +x $HOME/start_server.sh

WORKDIR /root

# 创建rclone配置文件
RUN rclone config -h

CMD ["sh", "-c", "/root/start_server.sh"]
EXPOSE 5700

